use movies;

INSERT INTO MOVIESTAR(NAME, GENDER, BIRTHDATE)
VALUES 
	('Nicole Kidman', 'F', '1967-06-20');

SELECT * FROM MOVIEEXEC;

DELETE FROM MOVIEEXEC 
WHERE NETWORTH <10000000;

DELETE FROM MOVIESTAR
WHERE ADDRESS IS NULL;

UPDATE MOVIEEXEC
	SET NAME = 'Pres. ' + Name
WHERE NAME IN 
	(SELECT 
		MOVIEEXEC.NAME 
	FROM MOVIEEXEC
	JOIN MOVIE ON
		MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
	JOIN STUDIO ON 
		MOVIE.STUDIONAME = STUDIO.NAME
	);

/*
	UPDATE MOVIEEXEC
	SET NAME = SUBSTRING(NAME, 7, LEN(NAME));
*/
