USE Movies;


UPDATE MOVIEEXEC
	SET name = CONCAT_WS(' ', 'Pres.', name)
WHERE name IN 
(SELECT MOVIEEXEC.name FROM MOVIEEXEC
	JOIN MOVIE ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
	JOIN STUDIO ON MOVIE.STUDIONAME = STUDIO.NAME);

SELECT * FROM MOVIEEXEC;
