use movies;

SELECT 
	title, 
	year,
	name,
	ADDRESS
FROM MOVIE
JOIN studio ON
	STUDIO.name = movie.STUDIONAME
WHERE length > 120;

SELECT 
    STUDIO.NAME,
    STARNAME
FROM STUDIO
JOIN MOVIE ON	
    STUDIO.NAME = MOVIE.STUDIONAME
JOIN STARSIN ON 
    MOVIE.TITLE = STARSIN.MOVIETITLE
ORDER BY STUDIO.NAME;

SELECT 
	MOVIEEXEC.NAME
FROM STARSIN
JOIN movie ON
	movie.title = STARSIN.MOVIETITLE
JOIN MOVIEEXEC ON
	MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE starname = 'Harrison Ford';

SELECT 
	MOVIESTAR.NAME
FROM STUDIO
JOIN MOVIE ON
	MOVIE.STUDIONAME = STUDIO.NAME
JOIN STARSIN ON
	MOVIE.TITLE = STARSIN.MOVIETITLE
JOIN MOVIESTAR ON
	MOVIESTAR.NAME = STARSIN.STARNAME
WHERE
	studio.name = 'MGM' AND 
	MOVIESTAR.GENDER = 'F';

SELECT 
	MOVIEEXEC.NAME,
	MOVIE.TITLE
FROM MOVIEEXEC
JOIN MOVIE ON
	MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
WHERE MOVIEEXEC.CERT# = (
SELECT MOVIEEXEC.CERT# FROM MOVIE
JOIN MOVIEEXEC ON
	MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE title = 'Star Wars');

SELECT 
	NAME
FROM MOVIESTAR
LEFT JOIN STARSIN ON 
	MOVIESTAR.NAME = STARSIN.STARNAME
WHERE MOVIETITLE IS NULL;
