use movies;

SELECT * FROM MOVIEEXEC
WHERE
	NAME IN (
		SELECT NAME FROM MOVIESTAR
		WHERE NAME IN(
			SELECT name from MOVIEEXEC))
	AND NETWORTH > 10000000;

SELECT NAME FROM MOVIESTAR
WHERE 
	NAME NOT IN (
		SELECT NAME FROM MOVIEEXEC);
